export const masterTables = [
  { name: 'mast_country', label: 'Country', icon: '🌍' },
  { name: 'mast_region', label: 'Region', icon: '🗺️' },
  { name: 'mast_state', label: 'State', icon: '📍' },
  { name: 'mast_district', label: 'District', icon: '🏙️' },
  { name: 'mast_pincode', label: 'Pincode', icon: '📮' },
  { name: 'mast_place', label: 'Place', icon: '📌' },
  { name: 'mast_ability', label: 'Ability', icon: '💪' },
  { name: 'mast_activity', label: 'Activity', icon: '⚡' },
  { name: 'mast_aptitude', label: 'Aptitude', icon: '🧠' },
  { name: 'mast_attitude', label: 'Attitude', icon: '😊' },
  { name: 'mast_career_choice', label: 'Career Choice', icon: '🎯' },
  { name: 'mast_contact', label: 'Contact', icon: '📞' },
  { name: 'mast_data', label: 'Data', icon: '💾' },
  { name: 'mast_industry', label: 'Industry', icon: '🏭' },
  { name: 'mast_knowledge', label: 'Knowledge', icon: '📚' },
  { name: 'mast_lang', label: 'Language', icon: '🗣️' },
  { name: 'mast_leadtype', label: 'Lead Type', icon: '🔥' },
  { name: 'mast_outlook', label: 'Outlook', icon: '🔮' },
  { name: 'mast_pathway', label: 'Pathway', icon: '🛤️' },
  { name: 'mast_preference', label: 'Preference', icon: '⭐' },
  { name: 'mast_sector', label: 'Sector', icon: '🏢' },
  { name: 'mast_skills', label: 'Skills', icon: '🛠️' },
  { name: 'mast_status', label: 'Status', icon: '✅' },
  { name: 'mast_stem', label: 'STEM', icon: '🔬' },
  { name: 'mast_task', label: 'Task', icon: '📋' },
  { name: 'mast_technology', label: 'Technology', icon: '💻' },
  { name: 'mast_tools', label: 'Tools', icon: '🔧' },
  { name: 'mast_trait', label: 'Trait', icon: '🎭' },
  { name: 'mast_zone', label: 'Zone', icon: '🌐' },
  { name: 'users', label: 'Users', icon: '👥' },
  { name: 'user_template', label: 'User Template', icon: '📄' },
];

export type MasterTable = typeof masterTables[number];
